### ISSUE TITLE
Неправильная генерация ссылки 

### ISSUE THREAD

**Issue by broadcastaddress** [ITECOMMPAY/paymentpage-sdk-php#24]
Берем тестовый ключ  выданный поддержкой, берем код в примерах .. 
```
$payment_id='31744';
$payment_amount=850.00;
$payment_currency='RUB';
$project_id='1143';

$secret = 'd70a8934fc69574876f457fee25cc49397c93471ce7e4e845a3556e4d67a­ca5d81906fc8b04b1a0936d56d9178b9cdb1c9702b353ea5d5129ac27e65­acba7804';

 
$gate = new  ecommpay\Gate( $secret );

$ePayment = new ecommpay\Payment(
    $project_id, 
    $payment_id
);

$ePayment
    ->setPaymentAmount($payment_amount)
    ->setPaymentCurrency($payment_currency)
;
      
$url = $gate->getPurchasePaymentPageUrl($ePayment);
echo $url;
```

получаем урл 

https://paymentpage.ecommpay.com/payment?project_id=1143&payment_id=31744&payment_amount=850&payment_currency=RUB&signature=kipXpww9ciTvdefMfZTD7eylIP4poR9TTWSANXFsGRACxj7IkR2FH7PlNnq6wFeEUl8h2ZaFijjrWz5i6qGAdA%3D%3D

открываем а там The error has occurred. Please apply to Technical Support.

**Comment by zhukovra** [comment]
@broadcastaddress в приложенном вами примере $secret содержит два невидимых символа "мягкого переноса". Именно по этому получившаяся подпись не сходится.
![image](https://user-images.githubusercontent.com/289431/56854719-c6c47580-6943-11e9-8657-012da069da4c.png)
