### ISSUE TITLE
Configurable MODE e.g. card_tokenize

### ISSUE THREAD

**Issue by Kladislav** [ITECOMMPAY/paymentpage-sdk-php#31]
So i need to implement a ecommpay card tokenize form

**Comment by sbaronenkov** [comment]
https://developers.ecommpay.com/en/en_PP_Parameters.html
https://github.com/ITECOMMPAY/paymentpage-sdk-php/blob/master/src/Payment.php

```
$payment = new ecommpay\Payment('11', 'some payment id');
$payment
    ->setCustomerId('some customer id')
    ->setMode('card_tokenize');
```
